### ISSUE TITLE
Save button not enabled

### ISSUE THREAD

**Issue by accelerande** [accelerande/teldutala.fo#1] opened 2016-07-19 19:00 UTC
1. Create a new document and enter a line of text.
2. Do not press ENTER.
3. The Save button is disabled.
4. Press ENTER.
5. The Save button is enabled.

Shouldn't the Save button be enabled in step 3?

**Comment by PaoloLeva** [comment] 2016-09-07 18:08
Cannot reproduce. If I provide a title then as soon as I type the first character in the text box the "Save" button is enabled. 
Bjartur, could you verify if this is still an issue?

**Comment by Bjartensen** [comment] 2016-09-07 19:11
@PaoloLeva It's still there, but after playing with it some more I think I know when it happens.

1. Open a blank document
2. Start typing text in the box before entering a title
3. Now try entering a title
4. Save button should be greyed out

Can you reproduce the bug with those steps?

It doesn't let me save unless I start writing again in the textbox. So it seems it doesn't perform a check when entering in the title box. Almost any other action (changing voice gender, messing with the speed etc) seems to perform a check. Heiti/Title and Høvundur/Author don't perform this check it seems. If it's as I expect, also performing the check when editing the title should fix the bug.

Any workflow that involves entering the title as the last step will encounter this bug.

**Comment by PaoloLeva** [comment] 2016-09-09 12:56
Reproduced and fixed.
@Bjartensen please confirm and if OK close the issue.

**Comment by Bjartensen** [comment] 2016-09-09 15:25
@PaoloLeva Was not able to reproduce the bug now, so that seems fixed. However, the save button accepts an empty document (entering a title but nothing in the text box), which I think is good, but an error occurs when saving.

<pre>
Error.
An error occurred while processing your request.

Exception: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
Controller: Home
Action: Player 

   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at VoicePortalWeb.Controllers.HomeController.Player(PlayerViewModel model)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
</pre>

**Comment by PaoloLeva** [comment] 2016-09-09 19:00
Well spotted, I missed testing the empty document scenario! Fixed. Now empty documents are accepted. Hopefully now everything works as expected.

**Comment by Bjartensen** [comment] 2016-09-10 15:56
Yes, I think the save feature is fixed now.

**Closed by Bjartensen** 2016-09-10 15:56 UTC
Labels: bug, question
