### ISSUE TITLE
Associate Google Account doesn't work (Android)

### ISSUE THREAD

**Issue by Bjartensen** [accelerande/teldutala.fo#31] opened 2018-02-10 22:37 UTC
On the Android app when I try to get the registration code I can't associated my Google account.

# Images:
https://drive.google.com/open?id=0B-V5WEx_UAYidkRwVnhBNGI5SEI3Sl9ndU11SUJnUGo5OHRF
[Get Started]
https://drive.google.com/open?id=0B-V5WEx_UAYiSTB6b2MyY3YyTWUzai1vdGxtLU1kbkVpMmxj
[Open browser to get code]
https://drive.google.com/open?id=0B-V5WEx_UAYiRkVOVjF4bXpxV0VPdDRTZmJCYmRRWTBHQ2xz
[Google]
https://drive.google.com/open?id=0B-V5WEx_UAYiV1dEcGdPMkY3NnFhVEpvbHVaZnlJNDd2VUFN
[Register]
https://drive.google.com/open?id=0B-V5WEx_UAYidThnenVHRmJKcWlLTHUxdFktSVlFb3lWVXdn

**Comment by PaoloLeva** [comment] 2018-02-11 10:25
@Bjartensen we use the same login as the website (it is a way to link together your content from the website with the app). So you should be able to use the same login as teldutala.fo (where you also have a way to recover password).
If you get problems let me know and we'll reset your account. In some case we noticed that the website account created during the beta phase of the website got in some error state.

**Comment by Bjartensen** [comment] 2018-02-11 12:28
@PaoloLeva you can reset my account

**Comment by PaoloLeva** [comment] 2018-02-11 16:55
@Bjartensen account resetted

**Comment by Bjartensen** [comment] 2018-02-14 14:53
@PaoloLeva I still get the same error. I think it gets to the "successfully authenticated" (second to last image), but when I then have to input a username (which is labelled "email" by the way) and press `Register` I get to the last image of the original issue post.

**Comment by PaoloLeva** [comment] 2018-02-24 16:48
@Bjartensen I erased your older account. Could you try again?

**Comment by Bjartensen** [comment] 2018-02-24 17:02
@PaoloLeva I tried again with the same results. Do you think there is another account with that email? You can delete any account I have if there are more.

Referring to #32 I think you should be able to use the app without logging in.

**Comment by PaoloLeva** [comment] 2018-02-24 17:28
@Bjartensen 
I could reproduce the issue. The issue seems to be connected to creating the Google account from the mobile. I could go round it, it would help me if this workaround works for you as well.
Please do as follow:
1. go to [teldutala.fo](https://teldutala.fo) and create an account using the "Google" button
2. then go to the app and try login again using the "Google" button.

Let me know if it works for you in this way, so that we can locate the issue and debug it.

**Comment by Bjartensen** [comment] 2018-02-24 18:43
@PaoloLeva it worked! The app seems to be authenticated now.

**Comment by PaoloLeva** [comment] 2018-02-24 18:48
@Bjartensen great to know. Now you should see same and synced content on App and Website

**Comment by PaoloLeva** [comment] 2018-04-08 11:29
Closed as google inloggning works now

**Closed as completed by PaoloLeva** 2018-04-08 11:29 UTC
